section Section1;
shared #"meta" = let
  Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1GGuAhz24khVdbwaqzNqerYtNptKFUoXRPOxIpTWgQPg/edit?gid=1544873660#gid=1544873660"),
  #"Navigation 1" = Source{[name = "meta", ItemKind = "Table"]}[Data],
  #"Transform columns" = Table.TransformColumnTypes(#"Navigation 1", {{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type text}, {"Column10", type text}, {"Column11", type text}, {"Column12", type text}, {"Column13", type text}, {"Column14", type text}, {"Column15", type text}, {"Column16", type text}, {"Column17", type text}, {"Column18", type text}, {"Column19", type text}, {"Column20", type text}, {"Column21", type text}, {"Column22", type text}, {"Column23", type text}, {"Column24", type text}, {"Column25", type text}, {"Column26", type text}, {"Column27", type text}, {"Column28", type text}, {"Column29", type text}, {"Column30", type text}, {"Column31", type text}, {"Column32", type text}, {"Column33", type text}, {"Column34", type text}, {"Column35", type text}, {"Column36", type text}, {"Column37", type text}, {"Column38", type text}, {"Column39", type text}, {"Column40", type text}, {"Column41", type text}, {"Column42", type text}, {"Column43", type text}, {"Column44", type text}, {"Column45", type text}, {"Column46", type text}, {"Column47", type text}, {"Column48", type text}, {"Column49", type text}, {"Column50", type text}, {"Column51", type text}, {"Column52", type text}, {"Column53", type text}, {"Column54", type text}, {"Column55", type text}, {"Column56", type text}, {"Column57", type text}, {"Column58", type text}, {"Column59", type text}, {"Column60", type text}, {"Column61", type text}, {"Column62", type text}, {"Column63", type text}, {"Column64", type text}, {"Column65", type text}, {"Column66", type text}, {"Column67", type text}, {"Column68", type text}, {"Column69", type text}, {"Column70", type text}, {"Column71", type text}, {"Column72", type text}, {"Column73", type text}, {"Column74", type text}, {"Column75", type text}, {"Column76", type text}, {"Column77", type text}, {"Column78", type text}, {"Column79", type text}, {"Column80", type text}, {"Column81", type text}, {"Column82", type text}, {"Column83", type text}, {"Column84", type text}, {"Column85", type text}, {"Column86", type text}, {"Column87", type text}, {"Column88", type text}, {"Column89", type text}, {"Column90", type text}, {"Column91", type text}}),
  #"Replace errors" = Table.ReplaceErrorValues(#"Transform columns", {{"Column1", null}, {"Column2", null}, {"Column3", null}, {"Column4", null}, {"Column5", null}, {"Column6", null}, {"Column7", null}, {"Column8", null}, {"Column9", null}, {"Column10", null}, {"Column11", null}, {"Column12", null}, {"Column13", null}, {"Column14", null}, {"Column15", null}, {"Column16", null}, {"Column17", null}, {"Column18", null}, {"Column19", null}, {"Column20", null}, {"Column21", null}, {"Column22", null}, {"Column23", null}, {"Column24", null}, {"Column25", null}, {"Column26", null}, {"Column27", null}, {"Column28", null}, {"Column29", null}, {"Column30", null}, {"Column31", null}, {"Column32", null}, {"Column33", null}, {"Column34", null}, {"Column35", null}, {"Column36", null}, {"Column37", null}, {"Column38", null}, {"Column39", null}, {"Column40", null}, {"Column41", null}, {"Column42", null}, {"Column43", null}, {"Column44", null}, {"Column45", null}, {"Column46", null}, {"Column47", null}, {"Column48", null}, {"Column49", null}, {"Column50", null}, {"Column51", null}, {"Column52", null}, {"Column53", null}, {"Column54", null}, {"Column55", null}, {"Column56", null}, {"Column57", null}, {"Column58", null}, {"Column59", null}, {"Column60", null}, {"Column61", null}, {"Column62", null}, {"Column63", null}, {"Column64", null}, {"Column65", null}, {"Column66", null}, {"Column67", null}, {"Column68", null}, {"Column69", null}, {"Column70", null}, {"Column71", null}, {"Column72", null}, {"Column73", null}, {"Column74", null}, {"Column75", null}, {"Column76", null}, {"Column77", null}, {"Column78", null}, {"Column79", null}, {"Column80", null}, {"Column81", null}, {"Column82", null}, {"Column83", null}, {"Column84", null}, {"Column85", null}, {"Column86", null}, {"Column87", null}, {"Column88", null}, {"Column89", null}, {"Column90", null}, {"Column91", null}})
in
  #"Replace errors";
