table QA_Semantic_06
	lineageTag: dd7ea6da-bbc2-4d29-8bb2-c6cf3df29522

	column Column1
		dataType: string
		lineageTag: 562cf3c6-a182-47c6-bd1d-fae2f153953a
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		lineageTag: 767420be-b8d0-4ea6-8f53-c2c74f917711
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	partition QA_Semantic_06 = m
		mode: import
		source =
				let
				  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45W8k0sylbSUfJLzE1VUIrViVYyMQVys7PzS4sTc8ACpgZAgeLEXKXYWAA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t, Column2 = _t])
				in
				  Source

